[package]
name = "uwuki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
todel = { git = "https://github.com/eludris/todel", version = "0.1.0" }
tokio = { version = "1.21.1", features = ["rt-multi-thread"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
